/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package P2;

import java.awt.Color;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author MyPC
 */
public class ServerTCP extends javax.swing.JFrame {

    /**
     * Creates new form serverTCP
     */
    public ServerTCP() {
        initComponents();
        onlineUsers = new ArrayList<String>();
        SocketList = new ArrayList<Socket>();
        index = 0;
        tcpIndex = 0;
        this.USERSLIST = new DefaultListModel();
        this.OnlineUsersList.setModel(USERSLIST);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Activate = new javax.swing.JButton();
        serverPortnumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        serverStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Interface = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        OnlineUsersList = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Activate.setText("Start Listening");
        Activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivateActionPerformed(evt);
            }
        });

        serverPortnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverPortnumberActionPerformed(evt);
            }
        });

        usersInfo.setColumns(20);
        usersInfo.setRows(5);
        jScrollPane1.setViewportView(usersInfo);

        jLabel1.setText("Status");

        serverStatus.setToolTipText("");

        jLabel2.setText("Online");

        jLabel3.setText("Port:");

        jScrollPane4.setViewportView(OnlineUsersList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverStatus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Activate)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverPortnumber))
                    .addComponent(Interface, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Activate)
                    .addComponent(serverPortnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Interface, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(serverStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivateActionPerformed

        tport = serverPortno;
        serverPortno = serverPortnumber.getText();
        serverStatus.setText("Address : 127.0.0.1 Port : " + serverPortno);
        try {

            if (!tport.equals(serverPortno)) {
                myServer = new ServerSocket(Integer.parseInt(serverPortno));
                mySocket = myServer.accept();
                flag = 2;

            }

            writer = new PrintWriter(mySocket.getOutputStream(), true);
            scanner = new Scanner(mySocket.getInputStream());
            Thread tcpServer;
            tcpServer = new Thread(new Runnable() {
                @Override
                public void run() {
                    while (true) {

                        try {
                            if(flag != 2){
                            mySocket = myServer.accept();
                            writer = new PrintWriter(mySocket.getOutputStream(), true);
                            scanner = new Scanner(mySocket.getInputStream());
                            
                            }
                            cData = scanner.nextLine();
                            if (cData.charAt(0) == '1') {
                                onlineUsers.add(index, cData.substring(1));
                                index++;
                                USERSLIST.addElement(cData.substring(1));
                                usersInfo.append(cData.substring(1).split(",")[0] + " Has Connected\n");
                                SocketList.add(tcpIndex, mySocket);
                                for (int i = 0; i < SocketList.size(); i++) {
                                    out = new PrintWriter(SocketList.get(i).getOutputStream(), true);
                                    for (int j = 0; j < onlineUsers.size(); j++) {
                                        out.println(onlineUsers.get(j));
                                    }
                                }
                            } else if (cData.charAt(0) == '0') {
                                USERSLIST.removeElement(cData.substring(1));
                                usersInfo.append(cData.substring(1).split(",")[0] + " Has Disconnected\n");
                                int indexForDelete = onlineUsers.indexOf(cData.substring(1));
                                onlineUsers.remove(indexForDelete);
                                index--;
                                SocketList.remove(indexForDelete);
                                tcpIndex--;
                                for (int i = 0; i < SocketList.size(); i++) {
                                    out = new PrintWriter(SocketList.get(i).getOutputStream(), true);
                                    out.println("0" + cData.substring(1));
                                }
                            }
                            flag = 3; 
                        } catch (IOException ex) {
                            Logger.getLogger(ServerTCP.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
//               throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

            });
            tcpServer.start();
        } catch (IOException ex) {
            Logger.getLogger(ServerTCP.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ActivateActionPerformed

    private void serverPortnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverPortnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverPortnumberActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Enumeration<NetworkInterface> interfaces = null;
        try {
            interfaces = NetworkInterface.getNetworkInterfaces();
        } catch (SocketException ex) {

        }

        while (interfaces.hasMoreElements()) {
            NetworkInterface networkInterface = interfaces.nextElement();

            Enumeration<InetAddress> inetAddresses = networkInterface.getInetAddresses();

            while (inetAddresses.hasMoreElements()) {
                Interface.addItem(networkInterface.getDisplayName() + inetAddresses.nextElement().toString());
            }

        }

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerTCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerTCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Activate;
    private javax.swing.JComboBox<String> Interface;
    private javax.swing.JList<String> OnlineUsersList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField serverPortnumber;
    private javax.swing.JTextField serverStatus;
    private javax.swing.JTextArea usersInfo;
    // End of variables declaration//GEN-END:variables
    String serverPortno = " ", cData, LData, tport, lastAdded, check, checkport, checkData;
    String[] dataArray;
    ServerSocket myServer;
    int flag = 1, tcpIndex;
    Socket mySocket;
    PrintWriter writer;
    PrintWriter out;
    Scanner scanner;
    ArrayList<String> onlineUsers;
    ArrayList<Socket> SocketList;
    private final DefaultListModel USERSLIST;
    int index;
}
